const famousQuotes = [
    'Feedback is the most powerful performance-improvement tool at your disposal. Yet, it is also the most underutilized, misunderstood, and misrepresented.',
    'One of the most important factors influencing a person’s success—whether it’s personal or professional—is mindset.',
    'Effective decision making is not just about data or intuition; it\'s about combining the two in a thoughtful and intelligent way.',
    'Money is everywhere, yet mastering it can be elusive. It\'s one of the few things that can simultaneously provide great joy and destroy it.',
    'When we strive to become better than we are, everything around us becomes better too.',
    'Happiness is not the absence of problems, but the ability to deal with them.',
    'The key to living a story you\'re proud of is being willing to revise it.',
    'Mindfulness is the practice of paying attention in a way that creates space for insight.',
    'The only way to achieve greatness is by taking risks and embracing discomfort.',
    'Physical intelligence is not about perfect bodies, but about achieving your personal best in body and mind.',
    'The learning economy will reward not just skills acquisition but also the ability to learn from experience and continuously adapt.',
    'The education system should not only teach us what to learn, but how to learn.',
    'Stories are the most powerful tool we have for connecting with others, influencing them, and creating change.',
    'Reciprocity is a natural and powerful human behavior that helps lubricate the wheels of social interaction.',
    'Being able to operate within an ambiguous environment can be the differentiating factor between failure and success.',
    'The most important decision you make is to be in a good mood.',
    'Optimism isn\'t about ignoring problems, it\'s about confronting them head-on and finding the positive in every situation.',
    'When we hit the pause button, it allows us to step back from a situation, gain a different perspective, and make a more informed decision.',
    'Autonomy is not just about self-direction, but about finding meaning and purpose in our actions and being fully engaged in what we do.',
    'The funny thing about fun is that it\'s not just fun. It\'s also powerful, like a force of nature.',
    'Intelligence and knowledge can be powerful allies, but only if they are integrated with wisdom.',
    'Bad relationships are like smoking: they’ll kill you.',
    'The problem is not that you\'re not good enough. The problem is that you\'re too good to be stuck in a job that doesn\'t challenge you or fulfill you.',
    'Creating a problem statement is essential because it forces you to articulate what it is you\'re trying to solve.',
    'Believe it can be done. When you believe something can be done, really believe, your mind will find the ways to do it.',
    'Reinforcements are anything that follows a behavior and strengthens or increases the likelihood of that behavior occurring again in the future.',
    'When you change the way you look at things, the things you look at change.',
    'We must learn to dance in the rain and appreciate the beauty that exists even in the midst of a storm.',
    'Don\'t wait until you know who you are to get started.',
    'Share what you love, and the people who love the same things will find you.',
    'Intuition is like a muscle. The more you use it, the stronger it gets.',
    'Data is not just a tool for analysts or technologists, it\'s a tool for everyone.',
    'Great coaches understand that the performance and growth of their people isn\'t a linear process - it\'s more like a series of breakthroughs, each one building on the last.',
    'Success is not just about knowing what to do. It\'s about doing it. Information, plans and goals will not get you where you want to go.',
    'Your subconscious mind is like a bank, a sort of universal financial institution.',
    'Being awkward is not an impediment; it\'s an identity marker.',
    'Success is not about what you know, but how you use what you know.',
    'Value the relationship more than the opportunity.',
    'Small, consistent steps lead to great distances over time.',
    'Small actions can create big changes. Even tiny tweaks can lead to major transformations.',
    'Our modern environment is engineered to distract us, but by taking back control of our attention, we can reclaim our lives.',
    'There is less research into CQ (curiosity quotient); this concerns having a "hungry mind"; people with a higher CQ tend to be more inquisitive and open to new experiences.',
    'Curiosity is the foundation of learning, growth, and success.',
    'Small daily choices lead to big changes over time.',
    'Procrastination is a habit, and habits can be changed.',
    'Making good decisions requires both critical thinking and creative thinking.',
    'Innovation doesn\'t always require big, disruptive ideas. Small ideas can be just as powerful.',
    'Flexing is about trying new things, learning from them, and adjusting your approach as you go.',
    'The best leaders inspire others through their words, actions, and personal presence.',
];

export default famousQuotes;
